export default {
  FIRST_FIELD_AMOUNT: 19, 
  FIRST_FIELD_SELECTED_AMOUNT: 8, 
  SECOND_FIELD_AMOUNT: 2, 
  SECOND_FIELD_SELECTED_AMOUNT: 1, 
  FIRST_WINNING_SITUATION_FIRST_FIELD_SELECTED: 4,
  SECOND_WINNING_SITUATION_FIRST_FIELD_SELECTED: 3,
  SECOND_WINNING_SITUATION_SECOND_FIELD_SELECTED: 1,
}